"""Analyse de fairness (genre, tranche d'age) du champion d'une campagne.

Ne relance rien : relit les predictions holdout deja produites par
`run_home_credit_experiment.py` pour le champion d'une campagne, les joint
au dataset de features pour recuperer les attributs sensibles, puis exporte
un rapport de fairness dans le meme dossier de rapport (`fairness/`).
"""

from __future__ import annotations

import argparse
import logging
from pathlib import Path

from home_credit_mlops.data.io import read_table
from home_credit_mlops.fairness.report import export_fairness_report
from home_credit_mlops.logging_utils import configure_logging
from home_credit_mlops.reporting.campaign_lookup import (
    find_latest_campaign_metadata,
    load_champion_from_campaign,
)
from home_credit_mlops.settings import Settings, load_settings

LOGGER = logging.getLogger(__name__)

DEFAULT_SOURCE_CAMPAIGN = "lgbm_smote_full_cv5"
REPORTS_ROOT = Path("reports")


def _resolve_data_path(settings: Settings, data_path: str | None) -> Path:
    if data_path is None:
        return settings.dataset.default_train_path
    return Path(data_path).expanduser().resolve()


def _build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Compute fairness metrics (gender, age band) for a campaign's "
            "champion, from its already-computed holdout predictions."
        )
    )
    parser.add_argument("--config", default="configs/default.toml")
    parser.add_argument(
        "--data",
        default=None,
        help="Dataset used to fetch sensitive attributes (CODE_GENDER, AGE_YEARS). "
        "Defaults to the campaign's training dataset.",
    )
    parser.add_argument(
        "--source-campaign",
        default=DEFAULT_SOURCE_CAMPAIGN,
        help="Campaign name whose most recent campaign_metadata.json is analyzed.",
    )
    parser.add_argument(
        "--source-report-dir",
        default=None,
        help=(
            "Explicit path to a campaign report directory (containing "
            "campaign_metadata.json and predictions/). Overrides "
            "--source-campaign auto-discovery."
        ),
    )
    return parser


def main() -> None:
    configure_logging()
    parser = _build_argument_parser()
    args = parser.parse_args()

    settings = load_settings(args.config)

    source_metadata_path = (
        Path(args.source_report_dir) / "campaign_metadata.json"
        if args.source_report_dir
        else find_latest_campaign_metadata(REPORTS_ROOT, args.source_campaign)
    )
    if source_metadata_path is None or not source_metadata_path.exists():
        parser.error(
            f"No campaign_metadata.json found for campaign {args.source_campaign!r} "
            f"under {REPORTS_ROOT}. Provide --source-report-dir explicitly."
        )
        raise AssertionError("unreachable")

    champion = load_champion_from_campaign(source_metadata_path)
    report_dir = source_metadata_path.parent
    LOGGER.info(
        "Champion found: %s (candidate=%s, threshold=%s) from %s",
        champion["model_name"],
        champion["candidate_key"],
        champion["threshold"],
        champion["source_path"],
    )

    predictions_path = (
        report_dir / "predictions" / f"{champion['candidate_key']}_holdout_predictions.parquet"
    )
    if not predictions_path.exists():
        parser.error(
            f"Holdout predictions not found at {predictions_path}. This campaign "
            "report may have been generated by an older run, or its loose files "
            "were already cleaned up."
        )
        raise AssertionError("unreachable")

    LOGGER.info("Loading holdout predictions from %s", predictions_path)
    predictions = read_table(predictions_path)

    data_path = _resolve_data_path(settings, args.data)
    LOGGER.info("Loading sensitive attributes from %s", data_path)
    features = read_table(data_path)[["SK_ID_CURR", "CODE_GENDER", "AGE_YEARS"]]

    joined_frame = predictions.merge(features, on="SK_ID_CURR", how="inner")
    if len(joined_frame) != len(predictions):
        LOGGER.warning(
            "Joined frame has %s rows, but predictions had %s ; some holdout "
            "SK_ID_CURR were not found in %s.",
            len(joined_frame),
            len(predictions),
            data_path,
        )

    fairness_dir = report_dir / "fairness"
    result = export_fairness_report(
        joined_frame,
        fairness_dir,
        fn_cost=settings.business.fn_cost,
        fp_cost=settings.business.fp_cost,
        source_campaign=champion["campaign_name"],
        model_name=champion["candidate_key"],
        threshold=champion["threshold"],
    )

    gender_summary = result["gender_summary"]
    age_summary = result["age_summary"]
    print(f"Rapport de fairness ecrit dans : {fairness_dir}")
    print(
        "Genre - disparate impact ratio: "
        f"{gender_summary['disparate_impact_ratio']:.3f} "
        f"(flag={gender_summary['flag_disparate_impact']}), "
        f"equal opportunity difference: {gender_summary['equal_opportunity_difference']:.3f}"
    )
    print(
        "Tranche d'age - disparate impact ratio: "
        f"{age_summary['disparate_impact_ratio']:.3f} "
        f"(flag={age_summary['flag_disparate_impact']}), "
        f"equal opportunity difference: {age_summary['equal_opportunity_difference']:.3f}"
    )
    print(f"Classeur Excel : {result['workbook_path']}")


if __name__ == "__main__":
    main()
